import openai, os
import copy
from abc import ABC

class Bot(ABC):
    def __init__(self) -> None:
        super().__init__()
        self.API_KEY        =  os.environ['OPEN_AI_API_KEY']
    
    def create_msg(self, msg: str) -> None:
        
        ########################################################
        #   Call scraper to read the code
        #   Call string manipulator to modify the string  
        #   Compile Server and client description into one
        ########################################################
        
        self.messages = f"{msg}\n\n---\nGenerated by OpenAI bot."
    
    def call_gpt(self) -> str:
        chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=self.messages
        )
        reply = chat.choices[0].message.content
